# Site settings
title: Portfolio
description: Kiryl's portfolio to show up some of previous projects
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Kiryl Yemelyanenka
user_description: Results-oriented Swift iOS developer with 9+ years production experience creating high-performance, user-friendly mobile apps. Proficient in UIKit, SwiftUI, and HIG. Skilled in agile development and passionate about problem-solving. Eager to contribute to innovative projects and advance my mobile app development career.
user_title: iOS Developer
email: kirill.em@me.com
twitter_username: rbhbokka
github_username:  rbhbokka
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
